from sqlalchemy import String, Float, Integer, Text, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing import List, Optional, Any

from app.db.base import TenantAwareModel


class RiskSignal(TenantAwareModel):
    """Specific statistical or relational risk signal generated by a detector."""
    __tablename__ = "risk_signals"

    tender_id: Mapped[str] = mapped_column(String(36), ForeignKey("tenders.id", ondelete="CASCADE"), index=True, nullable=False)
    detector_code: Mapped[str] = mapped_column(String(50), index=True, nullable=False)  # PRICE_CLUSTERING, SHARED_DIRECTORS, etc.
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)  # low, medium, high, critical
    confidence: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)  # 0.0 to 1.0
    score_contribution: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    explanation: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(String(255), default="Tender records", nullable=False)
    records_count: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    evidence_items: Mapped[List["Evidence"]] = relationship("Evidence", back_populates="signal", cascade="all, delete-orphan")


class Evidence(TenantAwareModel):
    """Underlying evidence record supporting a risk signal."""
    __tablename__ = "evidence"

    signal_id: Mapped[str] = mapped_column(String(36), ForeignKey("risk_signals.id", ondelete="CASCADE"), index=True, nullable=False)
    source_type: Mapped[str] = mapped_column(String(100), nullable=False)  # BID_RECORDS, REGISTRY, HISTORICAL_AWARDS
    source_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    summary: Mapped[str] = mapped_column(String(500), nullable=False)
    data_payload: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    signal: Mapped["RiskSignal"] = relationship("RiskSignal", back_populates="evidence_items")
